### ISSUE TITLE
What scenarios does this code apply to？

### ISSUE THREAD

**Issue by xiafengdongzhi** [lanton97/MADDPG-Formation-Control#25]
Hello, I would like to ask what scenario this code is applicable to and whether satellite formation can use this code, thank you!

**Comment by lanton97** [comment]
The environment here is specifically designed for particle robot kinematics for a formation control problem with collision avoidance. As such, it is focussed on a more abstract, 2-dimensional system that isn't a one to one mapping with a satellite control problem. Additionally, I am not actively maintaining this code, and so it may be incompatible with newer versions of Gym and TF.

That said, the MADDPG code is decoupled from the individual dynamics. It should be possible to modify the environment code to add an additional spatial dimension and the desired satellite kinematics/dynamics, or to port the MADDPG code to a different simulator that conforms with the Gym interfaces.

**Comment by xiafengdongzhi** [comment]
Thanks!!!
